// =============================================================================
// useGameAudio.js — HTML5 Audio implementation
// =============================================================================
// HISTORY:
//   The earlier implementation of this hook used the Web Audio API
//   (AudioContext + OscillatorNode + GainNode) to synthesize every game
//   sound at runtime. That worked perfectly in every desktop and mobile
//   browser, but produced ZERO audible output inside the production Android
//   WebView used by Capacitor. After extensive diagnostics — silent-WAV
//   primer, MainActivity audio-stream pinning, master-gain verification,
//   on-screen log overlay — we proved that the WebView's Web Audio output
//   was being routed to a phantom sink even with ctx.state==='running' and
//   masterGain===1.0. A side-by-side A/B in Settings ("Test Tone" via Web
//   Audio vs. "Test File" via <audio>) confirmed the diagnosis: HTML5 audio
//   plays, Web Audio is silent.
//
// SOLUTION:
//   Pre-render every game sound to a WAV file at build time (see
//   public/sounds/*.wav, generated by scripts/generate-audio-assets.py
//   conceptually — the files are checked into the repo so no build step is
//   required). At runtime, play them through HTMLAudioElement instances,
//   which use Android's native MediaPlayer pipeline — the path that's
//   already proven to work in this WebView.
//
// PUBLIC API:
//   IDENTICAL to the Web Audio version. Every consumer (GameCanvas, Game,
//   SettingsModal) keeps working without modification. The function names,
//   call signatures, and behavior (early-return when sound is disabled,
//   thunder scheduling tied to rain, ambient piano on a random loop) are
//   all preserved.
//
// IMPLEMENTATION NOTES:
//   - Each sound has a small POOL of HTMLAudioElement instances. This lets
//     us overlap rapid drops without the "play() interrupted by new load"
//     issue you'd get from a single shared element.
//   - HTMLAudioElement.play() returns a Promise; we swallow rejections
//     because Android sometimes rejects when the element is preempted, but
//     the audio still plays. Logging is kept for diagnostics.
//   - Rain uses a single element with .loop=true. Volume is faded via the
//     element's .volume property (not Web Audio) over a setInterval.
//   - Thunder uses a recursive setTimeout chain so each interval is freshly
//     random in 8–20s (the bug ChatGPT flagged in the previous version).
//   - The ambient piano uses the same recursive-setTimeout pattern.
//   - initAudio() still primes via the silent-WAV trick on first gesture —
//     this remains useful for the first <audio> playback latency.
// =============================================================================

import { useRef, useCallback, useEffect } from 'react';
import { dlog } from '@/lib/debugLog';
import { primeAudio } from '@/lib/audioPrimer';

// -- Asset URLs ---------------------------------------------------------------
// Static paths under /public/sounds. The leading '/' resolves correctly in
// both Vite dev server and the bundled Capacitor build.
const DROP_URLS  = Array.from({ length: 8 }, (_, i) => `/sounds/drop-${i}.wav`);
const PIANO_URLS = Array.from({ length: 13 }, (_, i) => `/sounds/piano-${i}.wav`);
const MISS_URL    = '/sounds/miss.wav';
const WIN_URL     = '/sounds/win.wav';
const LOSE_URL    = '/sounds/lose.wav';
const POWERUP_URL = '/sounds/powerup.wav';
const SPILL_URL   = '/sounds/spill.wav';
const THUNDER_URL = '/sounds/thunder.wav';
const RAIN_URL    = '/sounds/rain.wav';
const TEST_URL    = '/test-beep.wav';

// -- Audio element pool helper ------------------------------------------------
// For sounds that may fire rapidly (drop catch, piano notes), keep N
// preloaded HTMLAudioElement instances and round-robin through them.
// POOL_SIZE=4 is enough to overlap the fastest possible drop cascade.
const POOL_SIZE = 4;

function makePool(url, volume = 1.0) {
  const elements = [];
  for (let i = 0; i < POOL_SIZE; i++) {
    const a = new Audio(url);
    a.preload = 'auto';
    a.volume = volume;
    elements.push(a);
  }
  let idx = 0;
  return {
    play() {
      const a = elements[idx];
      idx = (idx + 1) % POOL_SIZE;
      try {
        // Reset playback head so a half-finished previous play doesn't
        // make the new call silently no-op.
        a.currentTime = 0;
      } catch (_) { /* some Android builds throw on currentTime=0 before load */ }
      const p = a.play();
      if (p && typeof p.catch === 'function') {
        p.catch(err => dlog('Audio', 'play() rejected', { url, err: String(err) }));
      }
    },
    setVolume(v) {
      for (const a of elements) a.volume = v;
    },
    pauseAll() {
      for (const a of elements) {
        try { a.pause(); } catch (_) {}
      }
    },
  };
}

// =============================================================================
// useGameAudio hook
// =============================================================================
export const useGameAudio = (soundEnabled = true) => {
  // -- Element pools (lazily built once on first use) -----------------------
  const dropPoolsRef    = useRef(null);   // array of pools, one per variant
  const pianoPoolsRef   = useRef(null);   // array of pools, one per note
  const missPoolRef     = useRef(null);
  const winPoolRef      = useRef(null);
  const losePoolRef     = useRef(null);
  const powerupPoolRef  = useRef(null);
  const spillPoolRef    = useRef(null);
  const thunderPoolRef  = useRef(null);

  // Rain is a dedicated single element (looping, faded by .volume).
  const rainElementRef  = useRef(null);
  const rainFadeRef     = useRef(null);

  // Recursive timeout handles.
  const thunderTimerRef = useRef(null);
  const pianoTimerRef   = useRef(null);

  // Mirror soundEnabled into a ref so callbacks see the live value without
  // having to be recreated on every toggle.
  const soundEnabledRef = useRef(soundEnabled);
  soundEnabledRef.current = soundEnabled;

  // Diagnostic gate: log the first drop only (so the console isn't spammed).
  const firstDropLoggedRef = useRef(false);

  // ==========================================================================
  // Lazy initialization
  // ==========================================================================
  // Build every pool on the first user gesture. Building POOL_SIZE *
  // total-sounds Audio elements at module load would block startup on slow
  // devices; doing it once on first interaction is invisible to the user.
  const initAudio = useCallback(() => {
    primeAudio(); // legacy silent-WAV primer kept for safety
    if (dropPoolsRef.current) return; // already initialized

    dlog('Audio', 'initAudio: building element pools');
    dropPoolsRef.current   = DROP_URLS.map(u => makePool(u, 1.0));
    pianoPoolsRef.current  = PIANO_URLS.map(u => makePool(u, 0.4)); // quiet bg
    missPoolRef.current    = makePool(MISS_URL,    0.8);
    winPoolRef.current     = makePool(WIN_URL,     1.0);
    losePoolRef.current    = makePool(LOSE_URL,    1.0);
    powerupPoolRef.current = makePool(POWERUP_URL, 1.0);
    spillPoolRef.current   = makePool(SPILL_URL,   0.9);
    thunderPoolRef.current = makePool(THUNDER_URL, 0.8);
    dlog('Audio', 'initAudio: pools ready');
  }, []);

  // Diagnostic: 440Hz beep via the bundled test WAV. This is what the
  // "Test Tone" button in Settings calls. Now uses HTML5 audio (the same
  // path everything else uses) instead of Web Audio.
  const playTestTone = useCallback(() => {
    initAudio();
    try {
      const a = new Audio(TEST_URL);
      a.volume = 1.0;
      const p = a.play();
      if (p && typeof p.catch === 'function') {
        p.then(() => dlog('Audio', 'test tone: play ok'))
         .catch(err => dlog('Audio', 'test tone: play failed', { err: String(err) }));
      }
    } catch (err) {
      dlog('Audio', 'test tone: ctor threw', { err: String(err) });
    }
  }, [initAudio]);

  // ==========================================================================
  // Game event sounds
  // ==========================================================================
  const playDropCatch = useCallback(() => {
    if (!soundEnabledRef.current) {
      if (!firstDropLoggedRef.current) {
        firstDropLoggedRef.current = true;
        dlog('Audio', 'playDropCatch: sound disabled');
      }
      return;
    }
    initAudio();
    const pools = dropPoolsRef.current;
    if (!pools) return;
    if (!firstDropLoggedRef.current) {
      firstDropLoggedRef.current = true;
      dlog('Audio', 'playDropCatch: first call (HTML5 audio)');
    }
    // Pick a random variant so consecutive drops don't all sound identical.
    pools[Math.floor(Math.random() * pools.length)].play();
  }, [initAudio]);

  const playMiss = useCallback(() => {
    if (!soundEnabledRef.current) return;
    initAudio();
    missPoolRef.current && missPoolRef.current.play();
  }, [initAudio]);

  const playWin = useCallback(() => {
    if (!soundEnabledRef.current) return;
    initAudio();
    winPoolRef.current && winPoolRef.current.play();
  }, [initAudio]);

  const playLose = useCallback(() => {
    if (!soundEnabledRef.current) return;
    initAudio();
    losePoolRef.current && losePoolRef.current.play();
  }, [initAudio]);

  const playPowerUp = useCallback(() => {
    if (!soundEnabledRef.current) return;
    initAudio();
    powerupPoolRef.current && powerupPoolRef.current.play();
  }, [initAudio]);

  const playSpill = useCallback(() => {
    if (!soundEnabledRef.current) return;
    initAudio();
    spillPoolRef.current && spillPoolRef.current.play();
  }, [initAudio]);

  const playThunder = useCallback(() => {
    if (!soundEnabledRef.current) return;
    initAudio();
    thunderPoolRef.current && thunderPoolRef.current.play();
  }, [initAudio]);

  // ==========================================================================
  // Ambient rain (looping element + recursive thunder scheduler)
  // ==========================================================================
  const startRain = useCallback(() => {
    if (!soundEnabledRef.current) return;
    initAudio();

    if (!rainElementRef.current) {
      const a = new Audio(RAIN_URL);
      a.loop = true;
      a.preload = 'auto';
      a.volume = 0; // start silent and fade in
      rainElementRef.current = a;
    }
    const a = rainElementRef.current;
    const p = a.play();
    if (p && typeof p.catch === 'function') {
      p.catch(err => dlog('Audio', 'rain play() rejected', { err: String(err) }));
    }
    // Fade in to a comfortable bg volume over 2 seconds.
    const targetVol = 0.18;
    const fadeSteps = 40;
    const stepMs = 50;
    let step = 0;
    if (rainFadeRef.current) clearInterval(rainFadeRef.current);
    rainFadeRef.current = setInterval(() => {
      step++;
      a.volume = Math.min(targetVol, (targetVol / fadeSteps) * step);
      if (step >= fadeSteps) {
        clearInterval(rainFadeRef.current);
        rainFadeRef.current = null;
      }
    }, stepMs);

    // Kick off recursive thunder scheduling: 8–20s between strikes, fresh
    // random delay each iteration. This is the fix for the original bug
    // where thunder was scheduled with setInterval(fn, 8000 + random*12000)
    // — that only randomized once and then fired at a constant cadence.
    if (!thunderTimerRef.current) {
      const scheduleNext = () => {
        const delay = 8000 + Math.random() * 12000;
        thunderTimerRef.current = setTimeout(() => {
          thunderTimerRef.current = null;
          if (!rainElementRef.current || rainElementRef.current.paused) return;
          if (!soundEnabledRef.current) return;
          playThunder();
          scheduleNext();
        }, delay);
      };
      scheduleNext();
    }
  }, [initAudio, playThunder]);

  const stopRain = useCallback(() => {
    if (rainFadeRef.current) {
      clearInterval(rainFadeRef.current);
      rainFadeRef.current = null;
    }
    if (rainElementRef.current) {
      try {
        rainElementRef.current.pause();
        rainElementRef.current.currentTime = 0;
      } catch (_) {}
    }
    if (thunderTimerRef.current) {
      clearTimeout(thunderTimerRef.current);
      thunderTimerRef.current = null;
    }
  }, []);

  // ==========================================================================
  // Ambient background piano
  // ==========================================================================
  // Plays a soft random pentatonic note every 6–12s. Recursive setTimeout
  // so each interval is freshly random (the same fix as thunder).
  const startAmbientPiano = useCallback(() => {
    if (!soundEnabledRef.current) return;
    initAudio();
    if (pianoTimerRef.current) return; // already running

    const tick = () => {
      pianoTimerRef.current = null;
      if (!soundEnabledRef.current) return;
      const pools = pianoPoolsRef.current;
      if (!pools) return;
      pools[Math.floor(Math.random() * pools.length)].play();
      pianoTimerRef.current = setTimeout(tick, 6000 + Math.random() * 6000);
    };
    pianoTimerRef.current = setTimeout(tick, 6000 + Math.random() * 6000);
  }, [initAudio]);

  const stopAmbientPiano = useCallback(() => {
    if (pianoTimerRef.current) {
      clearTimeout(pianoTimerRef.current);
      pianoTimerRef.current = null;
    }
  }, []);

  // ==========================================================================
  // Mirror soundEnabled -> element volumes
  // ==========================================================================
  // When the user toggles sound off mid-game, fade rain to zero and pause
  // any active long-running elements. Short SFX (drop, miss, etc.) already
  // early-return at the per-call gate.
  useEffect(() => {
    if (!soundEnabled) {
      if (rainElementRef.current) {
        try { rainElementRef.current.pause(); } catch (_) {}
      }
      if (thunderTimerRef.current) {
        clearTimeout(thunderTimerRef.current);
        thunderTimerRef.current = null;
      }
      if (pianoTimerRef.current) {
        clearTimeout(pianoTimerRef.current);
        pianoTimerRef.current = null;
      }
    }
    // Note: we deliberately do NOT auto-restart rain/piano on toggle-on.
    // The game logic decides when ambience belongs; this hook just respects
    // the global mute.
  }, [soundEnabled]);

  // ==========================================================================
  // Cleanup on unmount
  // ==========================================================================
  useEffect(() => {
    return () => {
      stopRain();
      stopAmbientPiano();
      // Pause every pooled element so background tabs don't leak audio.
      const allPools = [
        ...(dropPoolsRef.current || []),
        ...(pianoPoolsRef.current || []),
        missPoolRef.current,
        winPoolRef.current,
        losePoolRef.current,
        powerupPoolRef.current,
        spillPoolRef.current,
        thunderPoolRef.current,
      ];
      for (const pool of allPools) {
        if (pool) pool.pauseAll();
      }
    };
  }, [stopRain, stopAmbientPiano]);

  // -- Public API -------------------------------------------------------------
  return {
    playDropCatch,
    playMiss,
    playWin,
    playLose,
    playPowerUp,
    playSpill,
    startRain,
    stopRain,
    playThunder,
    startAmbientPiano,
    stopAmbientPiano,
    // Aliases preserved for backward compatibility with older call sites.
    startBackgroundMusic: startAmbientPiano,
    stopBackgroundMusic:  stopAmbientPiano,
    playcatch:    playDropCatch,
    playCatMeow:  playMiss,
    initAudio,
    playTestTone,
  };
};
