// =============================================================================
// ENTRY POINT -- main.jsx
// =============================================================================
// This is the very first file executed when the app boots.
// Responsibilities:
//   1. Mount the React root onto the <div id="root"> in index.html
//   2. Register the service worker so the app can work offline
//   3. Automatically follow the OS dark/light preference unless the user
//      has already set a manual override via Settings
// =============================================================================

import React from 'react';
import ReactDOM from 'react-dom/client';
import App from '@/App.jsx';
import DebugOverlay from '@/components/DebugOverlay';
import '@/index.css';

// -- 1. Mount React app ------------------------------------------------------
ReactDOM.createRoot(document.getElementById('root')).render(
  <>
    <App />
    {/* On-screen log viewer for on-device debugging. Toggle pill is in top-right. */}
    <DebugOverlay />
  </>
);

// -- 2. Service Worker registration (enables offline caching) ----------------
// The sw.js file is generated by Vite's PWA plugin and handles asset caching.
// We silently ignore failures (e.g. unsupported browser, dev mode).
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {});
  });
}

// -- 3. OS dark/light mode sync -----------------------------------------------
// Listen for OS-level theme changes. If the user has NOT picked a manual
// preference in the Settings screen, we follow the OS automatically.
// If they have set one (stored in localStorage as 'puredrop_dark_mode'),
// we leave it alone and let their choice win.
const osColorScheme = window.matchMedia('(prefers-color-scheme: dark)');
osColorScheme.addEventListener('change', (e) => {
  const manualOverride = localStorage.getItem('puredrop_dark_mode');
  if (manualOverride !== null) return; // user set a preference -- don't touch it

  // Toggle the 'light' class on <html> so Tailwind's dark-mode strategy works
  if (e.matches) {
    document.documentElement.classList.remove('light');
  } else {
    document.documentElement.classList.add('light');
  }
});
